### PR TITLE
Restructure spec directory

### PR DESCRIPTION
**Pull request by andyw8**
By convention, the spec directory mirrors the lib directory, e.g.

https://github.com/thoughtbot/factory_bot/tree/master/spec

A handy benefit of this is easy toggling between the spec and
implementation in vim-ruby with `:A`.

### CODE REVIEW

**Comment by andyw8** [comment]
@dubroe To minimize conflicts, it's probably better to merge this after the others currently open.

**Comment by dubroe** [comment]
Thanks @andyw8

**Comment by dubroe** [comment]
@andyw8 I merged in master after merging in all of the other branches. So now we need to update .rubocop_todo.yml right? I'm not really familiar with this workflow.

**Comment by andyw8** [comment]
@dubroe Yeah, in this case it was easiest just to regenerate the todo list with `rubocop . --auto-gen-config`. I've pushed that.

**Pull request merged**
